import Head from "next/head";
import Image from "next/image";
import {
  usePrepareContractWrite,
  useContractWrite,
  useWaitForTransaction,
} from "wagmi";
import React, { useState } from "react";
import favicon from "../assets/favicon.ico";
import logo from "../assets/logo.svg";
import { Button } from "antd";
import { SwapOutlined } from "@ant-design/icons";
import NumericInput from "../components/NumericInput";
import currencyMap from "@/components/currencyMap";
import type { Currency, CurrencyV } from "@/components/currencyMap";
import {
  ETH_USDC_POOL,
  mavPoolAdress,
  mavPoolCalculateAbi,
} from "@/components/abi";
import { useDebounceFn } from "ahooks";
import { useAccount } from "wagmi";

import styles from "@/styles/Home.module.less";

export default function Home() {
  const [isNetworkSwitchHighlighted, setIsNetworkSwitchHighlighted] =
    useState(false);
  const [isConnectHighlighted, setIsConnectHighlighted] = useState(false);

  const [swapPair, setSwapPair] = useState<[CurrencyV, CurrencyV]>([
    { ...currencyMap.ETH, value: "" },
    { value: "" },
  ]);

  const { address } = useAccount();

  console.log({ address });

  // const debouncedInputValue = useDebounce(swapPair[0]?.value, { wait: 500 });

  // const debouncedOutputValue = useDebounce(swapPair[1]?.value, { wait: 500 });

  const { config } = usePrepareContractWrite({
    address: mavPoolAdress,
    abi: mavPoolCalculateAbi,
    functionName: "calculateSwap",
    args: [
      ETH_USDC_POOL,
      Number(swapPair[0]?.value),
      (swapPair[0]?.address || "0") < (swapPair[1]?.address || "0"),
      false,
      0,
    ],
    // enabled: true,
  });

  const { data, write } = useContractWrite(config);

  // const { isLoading, isSuccess } =
  useWaitForTransaction({
    hash: data?.hash,
  });

  // useEffect(() => {
  //   write?.();
  // }, [debouncedInputValue]);

  const closeAll = () => {
    setIsNetworkSwitchHighlighted(false);
    setIsConnectHighlighted(false);
  };

  const onCurrencySelect = (currency: Currency, index: 0 | 1 = 0) => {
    console.log({ currency, swapPair, index });
    if (currency.symbol === swapPair[1 - index].symbol) {
      setSwapPair((sp) => {
        return [sp[1], sp[0]];
      });
    } else {
      setSwapPair((sp) => {
        sp[index] = { ...currency, value: sp[index].value };
        return [...sp];
      });
    }
  };

  const onClickOrder = () => {
    setSwapPair((sp) => {
      return [sp[1], sp[0]];
    });
  };

  const {
    run: debounceInputAmountChange,
    // cancel,
    // flush,
  } = useDebounceFn(
    () => {
      // setSwapPair((sp) => [{ ...sp[0], value: v }, sp[1]]);
      write?.();
    },
    {
      wait: 500,
    }
  );

  const onInputAmountChange = (v: string) => {
    setSwapPair((sp) => [{ ...sp[0], value: v }, sp[1]]);
    if (v && v! == swapPair[0].value && swapPair.every((sp) => !!sp.address)) {
      debounceInputAmountChange();
    }
  };

  return (
    <>
      <Head>
        <title>AdamSwap</title>
        <meta name="description" content="Generated by create-wc-dapp" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={favicon.src} />
      </Head>
      <header>
        <div
          className={styles.backdrop}
          style={{
            opacity: isConnectHighlighted || isNetworkSwitchHighlighted ? 1 : 0,
          }}
        />
        <div className={styles.header}>
          <div className={styles.logo}>
            <Image src={logo.src} alt="EasySwap" height="32" width="203" />
          </div>
          <div className={styles.buttons}>
            <div
              onClick={closeAll}
              className={`${styles.highlight} ${
                isNetworkSwitchHighlighted ? styles.highlightSelected : ``
              }`}
            >
              <w3m-network-button />
            </div>
            <div
              onClick={closeAll}
              className={`${styles.highlight} ${
                isConnectHighlighted ? styles.highlightSelected : ``
              }`}
            >
              <w3m-button />
            </div>
          </div>
        </div>
      </header>
      <main className={styles.main}>
        <div className={styles.wrapper}>
          <div className={styles.container}>
            <div className={styles.title}>Swap</div>
            <NumericInput
              tip="Pay"
              index={0}
              swapPair={swapPair}
              onSelect={(e) => onCurrencySelect(e, 0)}
              onChange={onInputAmountChange}
            />
            <div className={styles.divide}>
              <div className={styles.swapIcon} onClick={onClickOrder}>
                <SwapOutlined />
              </div>
            </div>
            <NumericInput
              tip="Receive"
              index={1}
              swapPair={swapPair}
              onSelect={(e) => onCurrencySelect(e, 1)}
              onChange={(v) =>
                setSwapPair((sp) => [sp[0], { ...sp[1], value: v }])
              }
            />
            <Button
              className="swap-primary-btn"
              type="primary"
              size="large"
              disabled={swapPair.some((sp) => !sp.symbol || !sp.value)}
            >
              {swapPair.some((sp) => !sp.symbol) ? "Select a token" : "Swap"}
            </Button>
          </div>
        </div>
      </main>
    </>
  );
}
